#!/bin/bash
apt update
apt install software-properties-common -y
apt-add-repository --yes --update ppa:ansible/ansible
apt update
apt install ansible -y
apt install nginx -y
apt install git -y
apt install stress -y
git clone -b Azure-branch https://github.com/bkrraj/ansibletemplatetesting.git  /myrepo
######USE aws-autoscaling branch for testing aws autoscaling##########################
######GIVE ONLY ABOVE IN THE USER DATA FOR AMI IMAGE FOR AWS AUTOSCALING##########
#
#####GIVE BELOW IN THE LAUNCH CONFIG USERDATA#####################################
ansible-playbook /myrepo/playbook.yaml

#For Azure

#cloud-config
runcmd:
  - ansible-playbook /myrepo/playbook.yaml


runcmd:
  - git clone --branch Azure-branch https://github.com/bkrraj/ansibletemplatetesting.git  /myrepo
  - cd / && ansible-playbook playbook.yml
